-- Supabase schema aligned with lib/supabase-db.js

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  google_id text not null unique,
  email text not null,
  name text,
  created_at bigint not null,
  updated_at bigint
);

create table if not exists public.databases (
  id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  created_at bigint not null,
  updated_at bigint
);

create table if not exists public.officials (
  id text primary key,
  database_id text not null references public.databases(id) on delete cascade,
  name text not null,
  email text,
  gender text,
  title text,
  department text,
  position text,
  stament text,
  is_boss boolean default false,
  boss_name text,
  boss_position text,
  boss_email text,
  created_at bigint,
  updated_at bigint
);

create table if not exists public.templates (
  id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  subject text,
  body text,
  created_at bigint not null,
  updated_at bigint
);

create table if not exists public.current_template (
  user_id bigint primary key references public.users(id) on delete cascade,
  subject text,
  body text,
  updated_at bigint
);

create table if not exists public.sent_history (
  user_id bigint not null references public.users(id) on delete cascade,
  official_id text not null references public.officials(id) on delete cascade,
  sent_at bigint not null,
  primary key (user_id, official_id)
);

create table if not exists public.user_settings (
  user_id bigint primary key references public.users(id) on delete cascade,
  active_db_id text references public.databases(id) on delete set null,
  updated_at bigint
);

create index if not exists idx_databases_user_id on public.databases(user_id);
create index if not exists idx_officials_database_id on public.officials(database_id);
create index if not exists idx_templates_user_id on public.templates(user_id);
create index if not exists idx_sent_history_user_id on public.sent_history(user_id);
